services:
  back:
    image: node
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
      DB_USER: node
      DB_PASS: node
      DB_NAME: chat
      DB_ADDRESS: mongodb://mongo:27017
    volumes:
      - ./back-end:/app
    working_dir: /app
    command: npm start

  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: node
      MONGO_INITDB_ROOT_PASSWORD: node
    volumes:
      - ./docker/mongo/data:/data/db

  front:
    image: caddy
    ports:
      - 80:80
    volumes:
      - ./front-end:/app
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./docker/caddy/data:/data
      - ./docker/caddy/config:/config
